name: Publish
on:
  push: ## pr merged
    ## only works on master branch
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - run: npm set config loglevel=info
      - name: Install
        run: npm ci --verbose || npm i --verbose
      - name: Prepare Git
        run: |
          git clean -df
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Update Version
        run: npx standard-version
      - name: Check version to publish to NPM
        run: npx can-npm-publish
      - name: Publish_NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: "${{ secrets.NPM_AUTH_TOKEN }}"
      - name: Git_Tag
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
